apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
  labels:
    app: weather-app
spec:
  type: LoadBalancer
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      port: 5000        # The port on which the service will be accessible
      targetPort: 5000  # The port on which the weather app runs inside the container